server:
  port: 8080
  jetty:
    threadPool:
      maxThreads: 16
      minThreads: 4
      idleTimeout: 30000
spring:
  profiles:
    include: rest-schedule, telegram-schedule, web-schedule, telegram-rest
  http:
    multipart:
      max-file-size: 64MB
      max-request-size: 64MB
  datasource:
    url: jdbc:firebirdsql:localhost/3050:mkr
    username: "OTKACHOV"
    password: "Fuffy-20-21"
logging:
  file: ../logs/knuca-schedule.log
  level.org.springframework.web: DEBUG
api:
  swagger:
    path: "/api/docs"
    basePackage: "com.theopus"
telegram.bot:
  username: "KNUCA_InfoBot"
  token: "395659381:AAGf6YTIAEgwNYeTjrSRPPeSnUGEZLEU81s"
  metrics.google.tag: "UA-112398090-1"
  send.rate.per.sec: 29
  db.file: "knuca-schedule.db"

---
spring:
  profiles: prod
  datasource:
    url: jdbc:firebirdsql:194.28.103.11/3050:mkr
  telegram.bot:
    username: "KNUCA_ScheduleBot"
    token: "400574726:AAE2Lw4vrqTiMm3IQZos7oDOyxNQ-FS9Juk"

---
spring:
  profiles: local
  datasource:
    url: jdbc:firebirdsql:localhost/3050:mkr

---
spring:
  profiles: win-docker
  datasource:
    url: jdbc:firebirdsql:host.docker.internal/3050:mkr