server:
  port: 8080
  jetty:
    threadPool:
      maxThreads: 100
      minThreads: 10
      idleTimeout: 30000
spring:
  profiles:
    active: rest-schedule, telegram-schedule
  http:
    multipart:
      max-file-size: 64MB
      max-request-size: 64MB
logging:
  file: ../logs/knuca-rest.log
api:
  swagger:
    path: "/api/docs"
    basePackage: "com.theopus"
telegram.bot.username: "KNUCA_InfoBot"
telegram.bot.token: "395659381:AAGf6YTIAEgwNYeTjrSRPPeSnUGEZLEU81s"