server:
  port: 8080
  jetty:
    threadPool:
      maxThreads: 100
      minThreads: 10
      idleTimeout: 30000
spring:
  profiles:
    include: rest-schedule, telegram-schedule, web-schedule
  http:
    multipart:
      max-file-size: 64MB
      max-request-size: 64MB
  datasource:
    url: jdbc:firebirdsql:localhost/3050:mkr
    username: "OTKACHOV"
    password: "Fuffy-20-21"
logging:
  file: ../logs/knuca-schedule.log
  level.org.springframework.web: INFO
api:
  swagger:
    path: "/api/docs"
    basePackage: "com.theopus"
telegram.bot.username: "KNUCA_InfoBot"
telegram.bot.token: "395659381:AAGf6YTIAEgwNYeTjrSRPPeSnUGEZLEU81s"

---
spring:
  profiles: prod
  datasource:
    url: jdbc:firebirdsql:194.28.103.11/3050:mkr

---
spring:
  profiles: local
  datasource:
    url: jdbc:firebirdsql:localhost/3050:mkr

---
spring:
  profiles: win-docker
  datasource:
    url: jdbc:firebirdsql:host.docker.internal/3050:mkr