-- SELECT D3 as SNAME, D2 as FNAME, US4 as LTYPE, A2 as ROOM, R2 as DAT, R3 as LESSON_ORDER, FIO as TEACHERS
SELECT D3 as SNAME, D2 as FNAME, US4 as LTYPE, A2 as ROOMS, R2 as DAT, R3 as LESSON_ORDER, FIO as TEACHERS
FROM RAGRST(:LANG, :GROUP_ID , 0, 0, 0, 0, :DATE_FROM, :DATE_TO)